HPMarketplace/config/routes.rb
Rails.application.routes.draw do
  resources :quotations
  resources :tasks
  resources :task_sub_categories
  resources :task_categories
  resources :missions
  resources :main_objects
  resources :object_types
  resources :users
  resources :user_types
  resources :companies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

HPMarketplace/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

HPMarketplace/app/models/company.rb
class Company < ApplicationRecord
  has_many :user
end

HPMarketplace/app/models/main_object.rb
class MainObject < ApplicationRecord
  belongs_to :object_type
  belongs_to :tenant_or_owner
  belongs_to :pro_in_charge
end

HPMarketplace/app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :main_object
  belongs_to :user
end

HPMarketplace/app/models/object_type.rb
class ObjectType < ApplicationRecord
  belongs_to :tenant_or_owner, :class_name => 'user'
  belongs_to :pro_in_charge,  :class_name => 'user'
end

HPMarketplace/app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :task
end

HPMarketplace/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :task_category
  belongs_to :task_sub_category
  belongs_to :mission
  belongs_to :user
end

HPMarketplace/app/models/task_category.rb
class TaskCategory < ApplicationRecord
end

HPMarketplace/app/models/task_sub_category.rb
class TaskSubCategory < ApplicationRecord
  belongs_to :task_category
end

HPMarketplace/app/models/user.rb
class User < ApplicationRecord
  belongs_to :company
  belongs_to :user_type
  has_many :tenant_or_owner, :class_name => 'main_object', :foreign_key => 'tenant_or_owner'
  has_many :pro_in_charge, :class_name => 'main_object', :foreign_key => 'pro_in_charge'
end

HPMarketplace/app/models/user_type.rb
class UserType < ApplicationRecord
end

HPMarketplace/app/controllers/main_objects_controller.rb
class MainObjectsController < ApplicationController
  before_action :set_main_object, only: [:show, :edit, :update, :destroy]

  # GET /main_objects
  # GET /main_objects.json
  def index
    @main_objects = MainObject.all
  end

  # GET /main_objects/1
  # GET /main_objects/1.json
  def show
  end

  # GET /main_objects/new
  def new
    @main_object = MainObject.new
  end

  # GET /main_objects/1/edit
  def edit
  end

  # POST /main_objects
  # POST /main_objects.json
  def create
    @main_object = MainObject.new(main_object_params)

    respond_to do |format|
      if @main_object.save
        format.html { redirect_to @main_object, notice: 'Main object was successfully created.' }
        format.json { render :show, status: :created, location: @main_object }
      else
        format.html { render :new }
        format.json { render json: @main_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /main_objects/1
  # PATCH/PUT /main_objects/1.json
  def update
    respond_to do |format|
      if @main_object.update(main_object_params)
        format.html { redirect_to @main_object, notice: 'Main object was successfully updated.' }
        format.json { render :show, status: :ok, location: @main_object }
      else
        format.html { render :edit }
        format.json { render json: @main_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /main_objects/1
  # DELETE /main_objects/1.json
  def destroy
    @main_object.destroy
    respond_to do |format|
      format.html { redirect_to main_objects_url, notice: 'Main object was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_main_object
      @main_object = MainObject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def main_object_params
      params.require(:main_object).permit(:adress1, :adress2, :zipcode, :city, :reference, :access_code, :appt_number, :surface_area, :object_type_id, :tenant_or_owner_id, :pro_in_charge_id)
    end
end

HPMarketplace/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:task_category_id, :task_sub_category_id, :description, :start_date, :finish_date, :deadline_date, :mission_id, :user_id)
    end
end

HPMarketplace/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :phone, :mobile, :email, :login, :password, :company_id, :usertype_id)
    end
end

HPMarketplace/app/helpers/application_helper.rb
module ApplicationHelper
end

HPMarketplace/app/helpers/companies_helper.rb
module CompaniesHelper
end

HPMarketplace/app/helpers/main_objects_helper.rb
module MainObjectsHelper
end

HPMarketplace/app/helpers/missions_helper.rb
module MissionsHelper
end

HPMarketplace/app/helpers/object_types_helper.rb
module ObjectTypesHelper
end

HPMarketplace/app/helpers/quotations_helper.rb
module QuotationsHelper
end

HPMarketplace/app/helpers/tasks_helper.rb
module TasksHelper
end

HPMarketplace/app/helpers/user_types_helper.rb
module UserTypesHelper
end

HPMarketplace/app/helpers/users_helper.rb
module UsersHelper
end

HPMarketplace/app/views/main_objects/_form.html.erb
<%= form_with(model: main_object, local: true) do |form| %>
  <% if main_object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(main_object.errors.count, "error") %> prohibited this main_object from being saved:</h2>

      <ul>
      <% main_object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :adress1 %>
    <%= form.text_field :adress1 %>
  </div>

  <div class="field">
    <%= form.label :adress2 %>
    <%= form.text_field :adress2 %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :reference %>
    <%= form.text_field :reference %>
  </div>

  <div class="field">
    <%= form.label :access_code %>
    <%= form.text_field :access_code %>
  </div>

  <div class="field">
    <%= form.label :appt_number %>
    <%= form.number_field :appt_number %>
  </div>

  <div class="field">
    <%= form.label :surface_area %>
    <%= form.text_field :surface_area %>
  </div>

  <div class="field">
    <%= form.label :object_type_id %>
    <%= form.text_field :object_type_id %>
  </div>

  <div class="field">
    <%= form.label :tenant_or_owner_id %>
    <%= form.text_field :tenant_or_owner_id %>
  </div>

  <div class="field">
    <%= form.label :pro_in_charge_id %>
    <%= form.text_field :pro_in_charge_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

HPMarketplace/app/views/main_objects/edit.html.erb
<h1>Editing Main Object</h1>

<%= render 'form', main_object: @main_object %>

<%= link_to 'Show', @main_object %> |
<%= link_to 'Back', main_objects_path %>

HPMarketplace/app/views/main_objects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Main Objects</h1>

<table>
  <thead>
    <tr>
      <th>Adress1</th>
      <th>Adress2</th>
      <th>Zipcode</th>
      <th>City</th>
      <th>Reference</th>
      <th>Access code</th>
      <th>Appt number</th>
      <th>Surface area</th>
      <th>Object type</th>
      <th>Tenant or owner</th>
      <th>Pro in charge</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @main_objects.each do |main_object| %>
      <tr>
        <td><%= main_object.adress1 %></td>
        <td><%= main_object.adress2 %></td>
        <td><%= main_object.zipcode %></td>
        <td><%= main_object.city %></td>
        <td><%= main_object.reference %></td>
        <td><%= main_object.access_code %></td>
        <td><%= main_object.appt_number %></td>
        <td><%= main_object.surface_area %></td>
        <td><%= main_object.object_type %></td>
        <td><%= main_object.tenant_or_owner %></td>
        <td><%= main_object.pro_in_charge %></td>
        <td><%= link_to 'Show', main_object %></td>
        <td><%= link_to 'Edit', edit_main_object_path(main_object) %></td>
        <td><%= link_to 'Destroy', main_object, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Main Object', new_main_object_path %>

HPMarketplace/app/views/main_objects/new.html.erb
<h1>New Main Object</h1>

<%= render 'form', main_object: @main_object %>

<%= link_to 'Back', main_objects_path %>

HPMarketplace/app/views/main_objects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Adress1:</strong>
  <%= @main_object.adress1 %>
</p>

<p>
  <strong>Adress2:</strong>
  <%= @main_object.adress2 %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @main_object.zipcode %>
</p>

<p>
  <strong>City:</strong>
  <%= @main_object.city %>
</p>

<p>
  <strong>Reference:</strong>
  <%= @main_object.reference %>
</p>

<p>
  <strong>Access code:</strong>
  <%= @main_object.access_code %>
</p>

<p>
  <strong>Appt number:</strong>
  <%= @main_object.appt_number %>
</p>

<p>
  <strong>Surface area:</strong>
  <%= @main_object.surface_area %>
</p>

<p>
  <strong>Object type:</strong>
  <%= @main_object.object_type %>
</p>

<p>
  <strong>Tenant or owner:</strong>
  <%= @main_object.tenant_or_owner %>
</p>

<p>
  <strong>Pro in charge:</strong>
  <%= @main_object.pro_in_charge %>
</p>

<%= link_to 'Edit', edit_main_object_path(@main_object) %> |
<%= link_to 'Back', main_objects_path %>